version: '3.7'

services:
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

  mongoclient:
    image: mongoclient/mongoclient
    ports:
      - 3000:3000
    volumes:
      - mongoclient_data:/data/db
    links:
      - mongo
    depends_on:
      - mongo

  api:
    build: ./src
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8088:8080
    volumes:
      - ./openapi.json:/usr/share/nginx/html/openapi.json:ro
    environment:
      - API_URL=http://localhost:8088/openapi.json

    
volumes:
  portainer_data:
  mongo_data:
  mongoclient_data: